apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-deployment-example-v110
  namespace: seldon
spec:
  name: sklearn-iris-deployment
  predictors:
  - componentSpecs:
    - spec:
        nodeName: master1
        containers:
        - image: albert-classifier:2.0
          imagePullPolicy: IfNotPresent
          name: sklearn-iris-classifier
          env:
          - name: MODEL_PATH
            value: /mnt/ai_platform_models/ckpt/1594103091
          volumeMounts:
          - name: model-share
            mountPath: /mnt
            readOnly: true
        volumes:
        - name: model-share
          nfs:
           server: 172.24.7.167
           path: /opt/nfs_file
    graph:
      children: []
      endpoint:
        type: REST
      name: sklearn-iris-classifier
      type: MODEL
    name: sklearn-iris-predictor
    replicas: 1