spring:
  profiles:
    active: dev

################################################################################
## Profile for dev environment
################################################################################
---

spring:
  profiles: dev
app:
  id: 19921217 # 使用的 Apollo 的项目（应用）编号
apollo:
  meta: http://172.18.9.61:8080 # Apollo Meta Server 地址
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
    namespaces: application # 使用的 Apollo 的命名空间，默认为 application。

################################################################################
## Profile for pro environment
################################################################################
---

spring:
  profiles: pro
app:
  id: 19921218 # 使用的 Apollo 的项目（应用）编号
apollo:
  meta: http://172.18.9.61:8080 # Apollo Meta Server 地址
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
    namespaces: application # 使用的 Apollo 的命名空间，默认为 application。








